sudo: true
language: java
jobs:
  include:
    - stage: deps
      name: "Install Node Dependencies"
      script: npm install
    - stage: test
      name: "Clojure Tests"
      script: clojure -Adev:test
    - name: "Clojurescript Tests"
      script: clojure -Adev:test-cljs
    - stage: deploy
      name: "GitHub Release"
      script: 
        - clojure -Sverbose -A:dev:compile-cljs
        - npm run build
      deploy:
        provider: releases
        api_key:
          secure: ZMIGQFXN6meWBSJAyzvF5mKMD+2+jm/P+ej3/xJYCpU9/R6BlsIophall8LYblS4gYziDbpEGCrdKZ2y5StatJ7bkqFYRkbQgGihCUqZodByMgsoe9Cx8v/Fkh1Gf4Y2gVQ/2hvWDEO/ZMTkw2/94WSLNEVtY16XKeb89dB+JuTZHzlRVPZqmuD48ZD1tkhCBvxiheiDP6ReKJh6FRWyrxZ0L4pj8yJKcVndqBwnyHNyfFTtZCuZ6gABCnKwng2wk1DQBAPFRY0HCMcu7/P2QP9541nhZZnBslodZ/h1DK+AtGNj12pPsuBYvpkYXA0euO7/qzUzM3gM6GaOB1FbIdih+orXwyNol6VXa2d+vGxp4UxFtq2A3EHRrpVHf198Wt1jhklffItG44gXyk7Coy5g06RFr7Ys3KIuD9gPjE/n5+jlzWqIaeNMD9k+YNYRibhXelFBODnJ9DuvOGauGMbQWDyHodvlRxd5dTedBWMNAF29DuvmRymDRXi/AzsR+rSvBH4hPs4/ie5ENNff0vtFK0H3Xewbffk0A4iIfGDDJA6JWqPZl6dtLen4zwUf+UoQSvLYzHSRH/RgxL//GCGWq29YX5QIqeTtUZ+AvBT9YPMNUOFUXPOKWntSz73kijR6eC4W1JeFHX5pYKbaGkckwoA8vkxt6SpZJwrE5k0=
        file:
        - pkg/cljs-travis-experiment-macos
        - pkg/cljs-travis-experiment-win.exe
        skip_cleanup: true
        draft: true
        on:
          tags: true
          repo: alzadude/cljs-travis-experiment
install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.358.sh
  - chmod +x linux-install-1.9.0.358.sh
  - sudo ./linux-install-1.9.0.358.sh
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cljs"
  - "$HOME/.gitlibs"
  - node_modules
  - ".cpcache"
  - cljs-test-runner-out