sudo: true
language: java
jobs:
  include:
    - stage: deps
      name: "Install Javascript Dependencies"
      script: npm install
    - stage: test
      name: "Clojure Tests"
      script: clj -Adev:test
    - name: "Clojurescript Tests"
      script: clj -Adev:test-cljs
    - stage: compile
      name: "Clojurescript Compilation"
      script: clj -Sverbose -A:dev:compile-cljs
    - stage: native-image
      name: "Native Image from Javascript"
      script: npm run build
install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.358.sh
  - chmod +x linux-install-1.9.0.358.sh
  - sudo ./linux-install-1.9.0.358.sh
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cljs
    - $HOME/.gitlibs
    - node_modules
    - .cpcache
    - cljs-test-runner-out